# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-16 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='手机名称')),
                ('image', models.ImageField(max_length=150, upload_to='mobile/image/%Y%m', verbose_name='手机图片')),
                ('desc', models.CharField(max_length=500, verbose_name='描述')),
                ('current_price', models.IntegerField(default=1, verbose_name='现价')),
                ('original_price', models.IntegerField(default=1, verbose_name='原价')),
                ('category', models.IntegerField(choices=[(1, '智能手机'), (2, '功能手机')])),
                ('appearance', models.IntegerField(choices=[(1, '触屏'), (2, '翻盖')])),
                ('series', models.IntegerField(choices=[(1, 'M系列'), (2, 'S系列'), (3, '天鉴系列'), (4, 'F系列'), (5, '金钢系列'), (6, '其他机型')])),
                ('sale_nums', models.IntegerField(default=0, verbose_name='销售量')),
                ('add_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='上市时间')),
                ('status', models.IntegerField(choices=[(1, '无'), (2, '新品'), (3, '首发'), (4, '热卖')])),
            ],
        ),
    ]
