# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-16 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=1, verbose_name='序号')),
                ('category', models.IntegerField(choices=[(1, '配件图片'), (2, '功能特色')])),
                ('image', models.ImageField(max_length=150, upload_to='mobile/mobile_image/%Y%m', verbose_name='手机图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mobile',
            options={'verbose_name': '手机信息', 'verbose_name_plural': '手机信息'},
        ),
        migrations.AddField(
            model_name='mobileimage',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.Mobile', verbose_name='手机'),
        ),
    ]
