# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-17 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0003_auto_20171017_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typicalspecification',
            name='screen_size',
            field=models.IntegerField(choices=[(1, '4.0英寸'), (2, '4.2英寸'), (3, '4.5英寸'), (4, '5.0英寸'), (5, '5.2英寸'), (6, '5.3英寸'), (7, '5.5英寸'), (8, '5.7英寸'), (9, '6.0英寸')], default=1, verbose_name='屏幕尺寸'),
        ),
    ]
