# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-17 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0004_auto_20171017_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='typicalspecification',
            name='wifi',
            field=models.IntegerField(choices=[(1, '支持'), (2, '不支持')], default=1, verbose_name='WIFI'),
        ),
    ]
