# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-17 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0006_typicalspecification_gyroscope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typicalspecification',
            name='os',
            field=models.IntegerField(choices=[(1, 'amigo3.0(Android5.0)'), (2, 'amigo3.1(Android5.1)'), (3, 'amigo3.2(Android6.0)'), (4, 'amigo3.5(Android5.1)'), (5, 'amigo3.5(Android6.0)'), (6, 'amigo4.0(Android7.0)'), (7, 'amigo5.0(Android7.1)'), (8, '天鉴os')], default=1, verbose_name='操作系统'),
        ),
    ]
