# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-18 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0007_auto_20171017_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='is_onsale',
            field=models.IntegerField(choices=[(1, '有货'), (2, '缺货')], default=1, verbose_name='是否有货'),
        ),
    ]
