# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-18 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0008_mobile_is_onsale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='current_price',
            new_name='price',
        ),
    ]
