# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-11 08:34
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='名称')),
                ('image', models.ImageField(default='service_hlep/deafult.png', upload_to='service_help/%Y%m', verbose_name='图片')),
                ('service_type', models.IntegerField(choices=[(1, '账号管理'), (2, '购物指南'), (3, '订单管理'), (4, '配送方式'), (5, '支付方式'), (6, '售后服务'), (7, '相关说明'), (8, '联系我们')], default=1, verbose_name='服务类型')),
                ('service_id', models.IntegerField(default=1, verbose_name='服务id')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='文章内容')),
                ('add_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
    ]
