# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-12 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_help', '0002_remove_servicehelp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehelp',
            name='service_type',
            field=models.IntegerField(choices=[(1, '账号管理'), (2, '购物指南'), (3, '订单管理'), (4, '配送方式'), (5, '支付方式'), (6, '售后服务'), (7, '相关说明'), (8, '联系我们'), (9, '关于手机售后FAQ'), (10, '关于手机售前FAQ'), (11, '产品使用')], default=1, verbose_name='服务类型'),
        ),
    ]
