# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-12 06:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_help', '0003_auto_20171012_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('mobile', models.CharField(default='', max_length=11, verbose_name='手机')),
                ('question_type', models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '建议')], default=1)),
                ('detail', models.CharField(default='', max_length=600, verbose_name='问题描述')),
                ('add_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
    ]
