# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-12 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_help', '0004_serviceuserask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuserask',
            name='detail',
            field=models.CharField(default='', max_length=300, verbose_name='问题描述'),
        ),
        migrations.AlterField(
            model_name='serviceuserask',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
    ]
