# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-12 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_help', '0006_experiencestore_stopimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=10, verbose_name='城市')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(default='', max_length=20, verbose_name='省份')),
            ],
        ),
        migrations.AlterField(
            model_name='experiencestore',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_help.City', verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='experiencestore',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_help.District', verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_help.District', verbose_name='省份'),
        ),
    ]
