# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-13 01:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_help', '0007_auto_20171012_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNetworkStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('category', models.IntegerField(choices=[(1, '特约服务站'), (2, '客服中心')], verbose_name='类别')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('tel', models.CharField(max_length=11, verbose_name='服务电话')),
                ('add_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': '省份', 'verbose_name_plural': '省份'},
        ),
        migrations.AlterModelOptions(
            name='experiencestore',
            options={'verbose_name': '体验店', 'verbose_name_plural': '体验店'},
        ),
        migrations.AlterModelOptions(
            name='servicehelp',
            options={'verbose_name': '服务帮助', 'verbose_name_plural': '服务帮助'},
        ),
        migrations.AlterModelOptions(
            name='stopimage',
            options={'verbose_name': '店铺图片', 'verbose_name_plural': '店铺图片'},
        ),
        migrations.AddField(
            model_name='servicenetworkstation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_help.City', verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='servicenetworkstation',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_help.District', verbose_name='省份'),
        ),
    ]
