# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-13 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_help', '0008_auto_20171013_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicenetworkstation',
            options={'verbose_name': '售后服务网点', 'verbose_name_plural': '售后服务网点'},
        ),
        migrations.AlterField(
            model_name='servicenetworkstation',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='服务电话'),
        ),
    ]
