# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-13 04:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_help', '0009_auto_20171013_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokenScreenQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=1, verbose_name='序号')),
                ('question', models.CharField(max_length=150, verbose_name='问题描述')),
                ('content', models.CharField(max_length=200, verbose_name='问题解决')),
                ('add_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '碎屏保障服务问题解答',
                'verbose_name_plural': '碎屏保障服务问题解答',
            },
        ),
    ]
