# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-13 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_help', '0010_brokenscreenquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokenscreenquestion',
            name='index',
        ),
        migrations.AddField(
            model_name='brokenscreenquestion',
            name='category',
            field=models.IntegerField(choices=[(1, '碎屏服务'), (2, '上门维修')], default=1, verbose_name='类别'),
        ),
    ]
