# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-13 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_help', '0011_auto_20171013_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokenscreenquestion',
            options={'verbose_name': '保障服务问题解答', 'verbose_name_plural': '保障服务问题解答'},
        ),
    ]
