# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-23 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartforvisitor',
            name='product_id',
            field=models.IntegerField(default=1, verbose_name='商品ID'),
        ),
    ]
