# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-23 00:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0002_cartforvisitor_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartForUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=1, verbose_name='商品ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('image', models.CharField(max_length=150, verbose_name='图片')),
                ('price', models.IntegerField(default=1, verbose_name='单价')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('total_price', models.IntegerField(default=1, verbose_name='小计')),
                ('add_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
