# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-23 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20171023_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsforuser',
            name='price',
            field=models.IntegerField(default=0, verbose_name='总价'),
        ),
    ]
