# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-24 06:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0006_auto_20171023_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=1, verbose_name='商品ID')),
                ('product_type', models.IntegerField(choices=[(1, '手机'), (2, '配件')], default=1, verbose_name='商品类型')),
                ('add_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '最近浏览',
                'verbose_name_plural': '最近浏览',
            },
        ),
    ]
