# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-24 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_recentlyview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyview',
            name='add_times',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='访问时间'),
        ),
    ]
