# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-24 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20171024_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyview',
            name='add_times',
            field=models.DateTimeField(auto_now=True, verbose_name='访问时间'),
        ),
    ]
