# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-27 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_auto_20171026_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_title', models.IntegerField(choices=[(1, '个人'), (2, '单位')], default=1, verbose_name='发票抬头')),
                ('inv_payee', models.CharField(default='', max_length=150, verbose_name='收货地址')),
                ('inv_phone', models.CharField(default='', max_length=11, verbose_name='联系方式')),
                ('inv_taxno', models.CharField(default='', max_length=18, verbose_name='身份证号')),
                ('inv_email', models.CharField(default='', max_length=50, verbose_name='邮箱')),
            ],
        ),
    ]
