# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-29 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0014_auto_20171029_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicinvoice',
            name='order_number',
            field=models.CharField(default='', max_length=25, verbose_name='订单号'),
        ),
    ]
