# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-07 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_electronicinvoice_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, verbose_name='订单编号')),
                ('is_playment', models.IntegerField(choices=[(0, '未支付'), (1, '已支付')], default=0, verbose_name='订单是否支付')),
                ('order_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='下单时间')),
                ('order_price', models.IntegerField(default=0, verbose_name='订单金额')),
                ('address', models.CharField(max_length=200, verbose_name='收货地址')),
                ('playment_type', models.IntegerField(choices=[(1, '在线支付'), (2, '货到付款')], default=1, verbose_name='支付方式')),
                ('delivery_type', models.IntegerField(choices=[(1, '顺丰速运')], default=1, verbose_name='配送方式')),
                ('invoice_msg', models.CharField(max_length=200, verbose_name='发票信息')),
                ('carts', models.CharField(max_length=1000000, verbose_name='商品清单')),
            ],
        ),
    ]
