# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-07 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0016_cartsorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartsorder',
            name='invoice_msg',
        ),
        migrations.AddField(
            model_name='cartsforuser',
            name='status',
            field=models.IntegerField(choices=[(0, '未结算'), (1, '已结算')], default=0, verbose_name='是否结算'),
        ),
    ]
