# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-07 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0017_auto_20171107_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('nick_name', models.CharField(max_length=50, verbose_name='别名')),
                ('image', models.ImageField(max_length=150, upload_to='', verbose_name='图片')),
                ('category', models.IntegerField(choices=[(1, '第三方平台支付'), (2, '快捷支付'), (3, '银行网银')])),
            ],
        ),
    ]
