# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-07 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0018_paymentbank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentbank',
            options={'verbose_name': '支付方式', 'verbose_name_plural': '支付方式'},
        ),
        migrations.AddField(
            model_name='cartsorder',
            name='payment_bank',
            field=models.CharField(default='', max_length=20, verbose_name='支付银行'),
        ),
        migrations.AlterField(
            model_name='paymentbank',
            name='image',
            field=models.ImageField(max_length=150, upload_to='paymentbank/%Y%m', verbose_name='图片'),
        ),
    ]
