# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-08 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0019_auto_20171107_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsorder',
            name='user_id',
            field=models.IntegerField(default=0, max_length=10, verbose_name='用户'),
        ),
    ]
