# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-08 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0020_cartsorder_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartsorder',
            name='is_playment',
            field=models.IntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '已取消')], default=1, verbose_name='订单是否支付'),
        ),
    ]
