# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-19 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(1, '保密'), (2, '男'), (3, '女')], default=1, verbose_name='性别'),
        ),
    ]
