# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-25 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverifyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='收件人')),
                ('mobile', models.CharField(default='', max_length=11, verbose_name='联系电话')),
                ('desc', models.CharField(default='', max_length=100, verbose_name='省市区')),
                ('address', models.CharField(default='', max_length=200, verbose_name='地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
