# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-25 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='desc',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='area',
            field=models.CharField(default='', max_length=20, verbose_name='区'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='', max_length=20, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='province',
            field=models.CharField(default='', max_length=20, verbose_name='省份'),
        ),
    ]
