# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-26 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171025_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': '收获地址', 'verbose_name_plural': '收获地址'},
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='name',
            new_name='consignee',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='area',
            new_name='town',
        ),
    ]
