# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-31 01:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='add_times',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
