# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-09 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userorder_add_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=20, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='province',
            field=models.CharField(default='', max_length=20, verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='town',
            field=models.CharField(default='', max_length=20, verbose_name='区县'),
        ),
    ]
