# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-13 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('desc', models.CharField(max_length=50, verbose_name='描述')),
                ('price', models.IntegerField(default=1, verbose_name='价格')),
                ('category', models.IntegerField(choices=[(1, '后盖'), (2, '保护壳/套'), (3, '电池'), (4, '耳机'), (5, '数据线'), (6, '保护膜'), (7, '充电器'), (8, '移动电源'), (9, '无线传输'), (10, '自拍杆')], default=1, verbose_name='类别')),
                ('adaptation', models.IntegerField(choices=[(1, 'M6S'), (2, 'Plus'), (3, 'M6'), (4, 'M6Plus'), (5, 'M2017'), (6, 'W909'), (7, 'S9'), (8, 'F106'), (9, 'F5')], default=1, verbose_name='适用机型')),
                ('sale_nums', models.IntegerField(default=0, verbose_name='销售量')),
                ('add_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='PartsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=150, upload_to='parts/%Y%m', verbose_name='图片')),
                ('category', models.IntegerField(choices=[(1, '配件图片'), (2, '功能特色')])),
                ('add_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.Parts', verbose_name='配件')),
            ],
        ),
        migrations.CreateModel(
            name='TypicalSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='参数名')),
                ('content', models.CharField(max_length=50, verbose_name='参数内容')),
                ('add_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.Parts', verbose_name='配件')),
            ],
        ),
    ]
