# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-13 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parts',
            options={'verbose_name': '配件信息', 'verbose_name_plural': '配件信息'},
        ),
        migrations.AlterModelOptions(
            name='partsimage',
            options={'verbose_name': '配件图片', 'verbose_name_plural': '配件图片'},
        ),
        migrations.AlterModelOptions(
            name='typicalspecification',
            options={'verbose_name': '参数规格', 'verbose_name_plural': '参数规格'},
        ),
        migrations.AddField(
            model_name='parts',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否在做活动'),
        ),
        migrations.AddField(
            model_name='parts',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否热卖'),
        ),
    ]
