# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-13 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20171013_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsimage',
            name='index',
            field=models.IntegerField(default=1, verbose_name='序号'),
        ),
    ]
