# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_partsimage_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='reference_proce',
            field=models.IntegerField(default=1, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='adaptation',
            field=models.IntegerField(choices=[(1, 'M6S'), (2, 'M7Plus'), (3, 'M6'), (4, 'M6Plus'), (5, 'M2017'), (6, 'W909'), (7, 'S9'), (8, 'F106'), (9, 'F5')], default=1, verbose_name='适用机型'),
        ),
    ]
