# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-14 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20171013_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='image',
            field=models.ImageField(default='parts/image/default.png', max_length=150, upload_to='parts/image/%Y%m', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='price',
            field=models.IntegerField(default=1, verbose_name='现价'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='reference_proce',
            field=models.IntegerField(default=1, verbose_name='原价'),
        ),
    ]
