# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-14 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_auto_20171014_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts',
            old_name='reference_proce',
            new_name='reference_price',
        ),
    ]
