# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-14 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20171014_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='status',
            field=models.IntegerField(choices=[(1, '有货'), (2, '无货')], default=1, verbose_name='是否有货'),
        ),
    ]
